Add LargeBlockSR to 8.2
xcp-ng-rpms/sm pull request #43
Opened 2024-05-06 08:45 UTC by Nambrok

Koji build (v8.2-incoming, scratch) : https://koji.xcp-ng.org/taskinfo?taskID=52508

2024-05-06 10:43 UTC, Wescoeur requested changes

2024-05-06 13:50 UTC, stormi approved these changes

2024-05-06 20:52 UTC, Wescoeur approved these changes

2024-05-14 16:04 UTC, merged

2024-05-14 16:05 UTC, stormi commented
Koji build to v8.2-incoming: http://koji.xcp-ng.org/taskinfo?taskID=53223